const flashcards = [
  // ── Verbs ──────────────────────────────────────────────────
  {
    id: 'card_v1',
    set_id: 'set_verbs',
    sentence_parts: ['저는 매일 ', '공부해요', '.'],
    key_index: 1,
    translation: 'I study every day.',
    sort_order: 1,
  },
  {
    id: 'card_v2',
    set_id: 'set_verbs',
    sentence_parts: ['오늘 친구를 ', '만났어요', '.'],
    key_index: 1,
    translation: 'I met a friend today.',
    sort_order: 2,
  },
  {
    id: 'card_v3',
    set_id: 'set_verbs',
    sentence_parts: ['저는 한국어를 ', '배우고', ' 싶어요.'],
    key_index: 1,
    translation: 'I want to learn Korean.',
    sort_order: 3,
  },
  {
    id: 'card_v4',
    set_id: 'set_verbs',
    sentence_parts: ['내일 ', '갈게요', '.'],
    key_index: 1,
    translation: "I'll go tomorrow.",
    sort_order: 4,
  },
  {
    id: 'card_v5',
    set_id: 'set_verbs',
    sentence_parts: ['밥을 ', '먹었어요', '.'],
    key_index: 1,
    translation: 'I ate a meal.',
    sort_order: 5,
  },
  {
    id: 'card_v6',
    set_id: 'set_verbs',
    sentence_parts: ['음악을 ', '들어요', '.'],
    key_index: 1,
    translation: 'I listen to music.',
    sort_order: 6,
  },
  {
    id: 'card_v7',
    set_id: 'set_verbs',
    sentence_parts: ['한국 드라마를 ', '봐요', '.'],
    key_index: 1,
    translation: 'I watch Korean dramas.',
    sort_order: 7,
  },
  {
    id: 'card_v8',
    set_id: 'set_verbs',
    sentence_parts: ['커피를 ', '마셔요', '.'],
    key_index: 1,
    translation: 'I drink coffee.',
    sort_order: 8,
  },
  {
    id: 'card_v9',
    set_id: 'set_verbs',
    sentence_parts: ['책을 ', '읽어요', '.'],
    key_index: 1,
    translation: 'I read a book.',
    sort_order: 9,
  },
  {
    id: 'card_v10',
    set_id: 'set_verbs',
    sentence_parts: ['집에 ', '돌아가요', '.'],
    key_index: 1,
    translation: 'I go back home.',
    sort_order: 10,
  },
  {
    id: 'card_v11',
    set_id: 'set_verbs',
    sentence_parts: ['전화를 ', '받았어요', '.'],
    key_index: 1,
    translation: 'I received a phone call.',
    sort_order: 11,
  },
  {
    id: 'card_v12',
    set_id: 'set_verbs',
    sentence_parts: ['숙제를 ', '했어요', '.'],
    key_index: 1,
    translation: 'I did my homework.',
    sort_order: 12,
  },
  {
    id: 'card_v13',
    set_id: 'set_verbs',
    sentence_parts: ['창문을 ', '열었어요', '.'],
    key_index: 1,
    translation: 'I opened the window.',
    sort_order: 13,
  },
  {
    id: 'card_v14',
    set_id: 'set_verbs',
    sentence_parts: ['문을 ', '닫았어요', '.'],
    key_index: 1,
    translation: 'I closed the door.',
    sort_order: 14,
  },
  {
    id: 'card_v15',
    set_id: 'set_verbs',
    sentence_parts: ['친구에게 ', '보냈어요', '.'],
    key_index: 1,
    translation: 'I sent it to a friend.',
    sort_order: 15,
  },
  {
    id: 'card_v16',
    set_id: 'set_verbs',
    sentence_parts: ['버스를 ', '기다려요', '.'],
    key_index: 1,
    translation: 'I wait for the bus.',
    sort_order: 16,
  },
  {
    id: 'card_v17',
    set_id: 'set_verbs',
    sentence_parts: ['노래를 ', '불러요', '.'],
    key_index: 1,
    translation: 'I sing a song.',
    sort_order: 17,
  },
  {
    id: 'card_v18',
    set_id: 'set_verbs',
    sentence_parts: ['운동을 ', '해요', '.'],
    key_index: 1,
    translation: 'I exercise.',
    sort_order: 18,
  },
  {
    id: 'card_v19',
    set_id: 'set_verbs',
    sentence_parts: ['사진을 ', '찍었어요', '.'],
    key_index: 1,
    translation: 'I took a photo.',
    sort_order: 19,
  },
  {
    id: 'card_v20',
    set_id: 'set_verbs',
    sentence_parts: ['일찍 ', '일어났어요', '.'],
    key_index: 1,
    translation: 'I woke up early.',
    sort_order: 20,
  },
  {
    id: 'card_v21',
    set_id: 'set_verbs',
    sentence_parts: ['이메일을 ', '썼어요', '.'],
    key_index: 1,
    translation: 'I wrote an email.',
    sort_order: 21,
  },
  {
    id: 'card_v22',
    set_id: 'set_verbs',
    sentence_parts: ['가방을 ', '챙겼어요', '.'],
    key_index: 1,
    translation: 'I packed my bag.',
    sort_order: 22,
  },
  {
    id: 'card_v23',
    set_id: 'set_verbs',
    sentence_parts: ['친구를 ', '도와줬어요', '.'],
    key_index: 1,
    translation: 'I helped my friend.',
    sort_order: 23,
  },
  {
    id: 'card_v24',
    set_id: 'set_verbs',
    sentence_parts: ['물을 ', '끓였어요', '.'],
    key_index: 1,
    translation: 'I boiled water.',
    sort_order: 24,
  },
  {
    id: 'card_v25',
    set_id: 'set_verbs',
    sentence_parts: ['차를 ', '운전해요', '.'],
    key_index: 1,
    translation: 'I drive a car.',
    sort_order: 25,
  },

  // ── Nouns ──────────────────────────────────────────────────
  {
    id: 'card_n1',
    set_id: 'set_nouns',
    sentence_parts: ['이것은 ', '사과', '예요.'],
    key_index: 1,
    translation: 'This is an apple.',
    sort_order: 1,
  },
  {
    id: 'card_n2',
    set_id: 'set_nouns',
    sentence_parts: ['저는 ', '학생', '이에요.'],
    key_index: 1,
    translation: 'I am a student.',
    sort_order: 2,
  },
  {
    id: 'card_n3',
    set_id: 'set_nouns',
    sentence_parts: ['그 ', '가게', '는 커요.'],
    key_index: 1,
    translation: 'That store is big.',
    sort_order: 3,
  },
  {
    id: 'card_n4',
    set_id: 'set_nouns',
    sentence_parts: ['우리 ', '가족', '은 다섯 명이에요.'],
    key_index: 1,
    translation: 'Our family has five members.',
    sort_order: 4,
  },
  {
    id: 'card_n5',
    set_id: 'set_nouns',
    sentence_parts: ['오늘 ', '날씨', '가 좋아요.'],
    key_index: 1,
    translation: "Today's weather is nice.",
    sort_order: 5,
  },
  {
    id: 'card_n6',
    set_id: 'set_nouns',
    sentence_parts: ['', '학교', '에 가요.'],
    key_index: 1,
    translation: 'I go to school.',
    sort_order: 6,
  },
  {
    id: 'card_n7',
    set_id: 'set_nouns',
    sentence_parts: ['이 ', '책', '은 재미있어요.'],
    key_index: 1,
    translation: 'This book is interesting.',
    sort_order: 7,
  },
  {
    id: 'card_n8',
    set_id: 'set_nouns',
    sentence_parts: ['', '친구', '가 왔어요.'],
    key_index: 1,
    translation: 'A friend came.',
    sort_order: 8,
  },
  {
    id: 'card_n9',
    set_id: 'set_nouns',
    sentence_parts: ['이 ', '나라', '가 아름다워요.'],
    key_index: 1,
    translation: 'This country is beautiful.',
    sort_order: 9,
  },
  {
    id: 'card_n10',
    set_id: 'set_nouns',
    sentence_parts: ['', '이름', '이 뭐예요?'],
    key_index: 1,
    translation: 'What is your name?',
    sort_order: 10,
  },
  {
    id: 'card_n11',
    set_id: 'set_nouns',
    sentence_parts: ['', '집', '이 멀어요.'],
    key_index: 1,
    translation: 'The house is far.',
    sort_order: 11,
  },
  {
    id: 'card_n12',
    set_id: 'set_nouns',
    sentence_parts: ['', '돈', '이 없어요.'],
    key_index: 1,
    translation: 'I have no money.',
    sort_order: 12,
  },
  {
    id: 'card_n13',
    set_id: 'set_nouns',
    sentence_parts: ['', '시간', '이 있어요?'],
    key_index: 1,
    translation: 'Do you have time?',
    sort_order: 13,
  },
  {
    id: 'card_n14',
    set_id: 'set_nouns',
    sentence_parts: ['', '회사', '에 다녀요.'],
    key_index: 1,
    translation: 'I work at a company.',
    sort_order: 14,
  },
  {
    id: 'card_n15',
    set_id: 'set_nouns',
    sentence_parts: ['저는 ', '선생님', '이에요.'],
    key_index: 1,
    translation: 'I am a teacher.',
    sort_order: 15,
  },
  {
    id: 'card_n16',
    set_id: 'set_nouns',
    sentence_parts: ['', '병원', '에 가야 해요.'],
    key_index: 1,
    translation: 'I need to go to the hospital.',
    sort_order: 16,
  },
  {
    id: 'card_n17',
    set_id: 'set_nouns',
    sentence_parts: ['', '전화번호', '가 뭐예요?'],
    key_index: 1,
    translation: 'What is your phone number?',
    sort_order: 17,
  },
  {
    id: 'card_n18',
    set_id: 'set_nouns',
    sentence_parts: ['', '주소', '를 알려주세요.'],
    key_index: 1,
    translation: 'Please tell me your address.',
    sort_order: 18,
  },
  {
    id: 'card_n19',
    set_id: 'set_nouns',
    sentence_parts: ['', '음식', '이 맛있어요.'],
    key_index: 1,
    translation: 'The food is delicious.',
    sort_order: 19,
  },
  {
    id: 'card_n20',
    set_id: 'set_nouns',
    sentence_parts: ['', '방', '이 깨끗해요.'],
    key_index: 1,
    translation: 'The room is clean.',
    sort_order: 20,
  },

  // ── Food & Drink ───────────────────────────────────────────
  {
    id: 'card_f1',
    set_id: 'set_food',
    sentence_parts: ['', '김치', '가 매워요.'],
    key_index: 1,
    translation: 'Kimchi is spicy.',
    sort_order: 1,
  },
  {
    id: 'card_f2',
    set_id: 'set_food',
    sentence_parts: ['', '비빔밥', ' 주세요.'],
    key_index: 1,
    translation: 'Bibimbap, please.',
    sort_order: 2,
  },
  {
    id: 'card_f3',
    set_id: 'set_food',
    sentence_parts: ['아이스 ', '아메리카노', ' 한 잔 주세요.'],
    key_index: 1,
    translation: 'One iced Americano, please.',
    sort_order: 3,
  },
  {
    id: 'card_f4',
    set_id: 'set_food',
    sentence_parts: ['이 ', '떡볶이', ' 정말 맛있어요!'],
    key_index: 1,
    translation: 'This tteokbokki is really delicious!',
    sort_order: 4,
  },
  {
    id: 'card_f5',
    set_id: 'set_food',
    sentence_parts: ['', '물', ' 주세요.'],
    key_index: 1,
    translation: 'Water, please.',
    sort_order: 5,
  },
  {
    id: 'card_f6',
    set_id: 'set_food',
    sentence_parts: ['', '삼겹살', '을 먹고 싶어요.'],
    key_index: 1,
    translation: 'I want to eat samgyeopsal.',
    sort_order: 6,
  },
  {
    id: 'card_f7',
    set_id: 'set_food',
    sentence_parts: ['', '냉면', '이 시원해요.'],
    key_index: 1,
    translation: 'Naengmyeon is refreshing.',
    sort_order: 7,
  },
  {
    id: 'card_f8',
    set_id: 'set_food',
    sentence_parts: ['', '순두부찌개', '가 뜨거워요.'],
    key_index: 1,
    translation: 'Sundubu jjigae is hot.',
    sort_order: 8,
  },
  {
    id: 'card_f9',
    set_id: 'set_food',
    sentence_parts: ['', '치킨', '을 시켰어요.'],
    key_index: 1,
    translation: 'I ordered fried chicken.',
    sort_order: 9,
  },
  {
    id: 'card_f10',
    set_id: 'set_food',
    sentence_parts: ['', '김밥', '을 만들었어요.'],
    key_index: 1,
    translation: 'I made gimbap.',
    sort_order: 10,
  },
  {
    id: 'card_f11',
    set_id: 'set_food',
    sentence_parts: ['', '라면', '이 맛있어요.'],
    key_index: 1,
    translation: 'Ramen is delicious.',
    sort_order: 11,
  },
  {
    id: 'card_f12',
    set_id: 'set_food',
    sentence_parts: ['', '소주', ' 한 잔 할까요?'],
    key_index: 1,
    translation: 'Shall we have a glass of soju?',
    sort_order: 12,
  },
  {
    id: 'card_f13',
    set_id: 'set_food',
    sentence_parts: ['', '빵', '을 샀어요.'],
    key_index: 1,
    translation: 'I bought bread.',
    sort_order: 13,
  },
  {
    id: 'card_f14',
    set_id: 'set_food',
    sentence_parts: ['', '과일', '이 달아요.'],
    key_index: 1,
    translation: 'The fruit is sweet.',
    sort_order: 14,
  },
  {
    id: 'card_f15',
    set_id: 'set_food',
    sentence_parts: ['', '도시락', '을 준비했어요.'],
    key_index: 1,
    translation: 'I prepared a lunchbox.',
    sort_order: 15,
  },
  {
    id: 'card_f16',
    set_id: 'set_food',
    sentence_parts: ['', '맥주', '를 마셨어요.'],
    key_index: 1,
    translation: 'I drank beer.',
    sort_order: 16,
  },
  {
    id: 'card_f17',
    set_id: 'set_food',
    sentence_parts: ['', '케이크', '를 잘랐어요.'],
    key_index: 1,
    translation: 'I cut the cake.',
    sort_order: 17,
  },
  {
    id: 'card_f18',
    set_id: 'set_food',
    sentence_parts: ['', '녹차', '를 좋아해요.'],
    key_index: 1,
    translation: 'I like green tea.',
    sort_order: 18,
  },
  {
    id: 'card_f19',
    set_id: 'set_food',
    sentence_parts: ['', '짜장면', '이 먹고 싶어요.'],
    key_index: 1,
    translation: 'I want to eat jjajangmyeon.',
    sort_order: 19,
  },
  {
    id: 'card_f20',
    set_id: 'set_food',
    sentence_parts: ['', '갈비', '가 맛있어요.'],
    key_index: 1,
    translation: 'Galbi is delicious.',
    sort_order: 20,
  },
  {
    id: 'card_f21',
    set_id: 'set_food',
    sentence_parts: ['', '된장찌개', '를 끓였어요.'],
    key_index: 1,
    translation: 'I made doenjang jjigae.',
    sort_order: 21,
  },
  {
    id: 'card_f22',
    set_id: 'set_food',
    sentence_parts: ['', '호떡', '이 달콤해요.'],
    key_index: 1,
    translation: 'Hotteok is sweet.',
    sort_order: 22,
  },
  {
    id: 'card_f23',
    set_id: 'set_food',
    sentence_parts: ['', '잡채', '를 만들었어요.'],
    key_index: 1,
    translation: 'I made japchae.',
    sort_order: 23,
  },
  {
    id: 'card_f24',
    set_id: 'set_food',
    sentence_parts: ['', '파전', '과 막걸리 주세요.'],
    key_index: 1,
    translation: 'Pajeon and makgeolli, please.',
    sort_order: 24,
  },
  {
    id: 'card_f25',
    set_id: 'set_food',
    sentence_parts: ['', '불고기', '가 유명해요.'],
    key_index: 1,
    translation: 'Bulgogi is famous.',
    sort_order: 25,
  },

  // ── K-Pop & Music ──────────────────────────────────────────
  {
    id: 'card_k1',
    set_id: 'set_kpop',
    sentence_parts: ['이 ', '노래', ' 좋아해요.'],
    key_index: 1,
    translation: 'I like this song.',
    sort_order: 1,
  },
  {
    id: 'card_k2',
    set_id: 'set_kpop',
    sentence_parts: ['', '콘서트', '에 가고 싶어요.'],
    key_index: 1,
    translation: 'I want to go to a concert.',
    sort_order: 2,
  },
  {
    id: 'card_k3',
    set_id: 'set_kpop',
    sentence_parts: ['', '가수', '가 춤을 잘 춰요.'],
    key_index: 1,
    translation: 'The singer dances well.',
    sort_order: 3,
  },
  {
    id: 'card_k4',
    set_id: 'set_kpop',
    sentence_parts: ['새 ', '앨범', '이 나왔어요.'],
    key_index: 1,
    translation: 'A new album came out.',
    sort_order: 4,
  },
  {
    id: 'card_k5',
    set_id: 'set_kpop',
    sentence_parts: ['', '팬미팅', '에 참가했어요.'],
    key_index: 1,
    translation: 'I attended a fan meeting.',
    sort_order: 5,
  },
  {
    id: 'card_k6',
    set_id: 'set_kpop',
    sentence_parts: ['', '뮤직비디오', '가 멋있어요.'],
    key_index: 1,
    translation: 'The music video is cool.',
    sort_order: 6,
  },
  {
    id: 'card_k7',
    set_id: 'set_kpop',
    sentence_parts: ['', '아이돌', '을 좋아해요.'],
    key_index: 1,
    translation: 'I like idols.',
    sort_order: 7,
  },
  {
    id: 'card_k8',
    set_id: 'set_kpop',
    sentence_parts: ['이 ', '가사', '가 감동적이에요.'],
    key_index: 1,
    translation: 'These lyrics are moving.',
    sort_order: 8,
  },
  {
    id: 'card_k9',
    set_id: 'set_kpop',
    sentence_parts: ['', '드라마', ' OST를 들어요.'],
    key_index: 1,
    translation: 'I listen to drama OSTs.',
    sort_order: 9,
  },
  {
    id: 'card_k10',
    set_id: 'set_kpop',
    sentence_parts: ['', '응원봉', '을 흔들었어요.'],
    key_index: 1,
    translation: 'I waved my light stick.',
    sort_order: 10,
  },
  {
    id: 'card_k11',
    set_id: 'set_kpop',
    sentence_parts: ['', '안무', '를 외웠어요.'],
    key_index: 1,
    translation: 'I memorized the choreography.',
    sort_order: 11,
  },
  {
    id: 'card_k12',
    set_id: 'set_kpop',
    sentence_parts: ['', '최애', '가 생겼어요.'],
    key_index: 1,
    translation: 'I have a new bias.',
    sort_order: 12,
  },
  {
    id: 'card_k13',
    set_id: 'set_kpop',
    sentence_parts: ['', '티켓팅', '에 성공했어요!'],
    key_index: 1,
    translation: 'I got concert tickets!',
    sort_order: 13,
  },
  {
    id: 'card_k14',
    set_id: 'set_kpop',
    sentence_parts: ['', '포토카드', '를 모아요.'],
    key_index: 1,
    translation: 'I collect photocards.',
    sort_order: 14,
  },
  {
    id: 'card_k15',
    set_id: 'set_kpop',
    sentence_parts: ['', '방송', '에 나왔어요.'],
    key_index: 1,
    translation: 'They appeared on a broadcast.',
    sort_order: 15,
  },

  // ── Travel ─────────────────────────────────────────────────
  {
    id: 'card_t1',
    set_id: 'set_travel',
    sentence_parts: ['', '공항', '이 어디예요?'],
    key_index: 1,
    translation: 'Where is the airport?',
    sort_order: 1,
  },
  {
    id: 'card_t2',
    set_id: 'set_travel',
    sentence_parts: ['', '호텔', '까지 얼마예요?'],
    key_index: 1,
    translation: 'How much to the hotel?',
    sort_order: 2,
  },
  {
    id: 'card_t3',
    set_id: 'set_travel',
    sentence_parts: ['', '지하철', ' 역이 어디예요?'],
    key_index: 1,
    translation: 'Where is the subway station?',
    sort_order: 3,
  },
  {
    id: 'card_t4',
    set_id: 'set_travel',
    sentence_parts: ['', '여권', ' 보여주세요.'],
    key_index: 1,
    translation: 'Please show your passport.',
    sort_order: 4,
  },
  {
    id: 'card_t5',
    set_id: 'set_travel',
    sentence_parts: ['', '택시', '를 불러주세요.'],
    key_index: 1,
    translation: 'Please call a taxi.',
    sort_order: 5,
  },
  {
    id: 'card_t6',
    set_id: 'set_travel',
    sentence_parts: ['', '환전', '을 하고 싶어요.'],
    key_index: 1,
    translation: 'I want to exchange money.',
    sort_order: 6,
  },
  {
    id: 'card_t7',
    set_id: 'set_travel',
    sentence_parts: ['', '관광지', '를 추천해 주세요.'],
    key_index: 1,
    translation: 'Please recommend tourist spots.',
    sort_order: 7,
  },
  {
    id: 'card_t8',
    set_id: 'set_travel',
    sentence_parts: ['체크인 ', '시간', '이 언제예요?'],
    key_index: 1,
    translation: 'What time is check-in?',
    sort_order: 8,
  },
  {
    id: 'card_t9',
    set_id: 'set_travel',
    sentence_parts: ['', '짐', '을 맡길 수 있어요?'],
    key_index: 1,
    translation: 'Can I store my luggage?',
    sort_order: 9,
  },
  {
    id: 'card_t10',
    set_id: 'set_travel',
    sentence_parts: ['', '버스', '가 몇 시에 출발해요?'],
    key_index: 1,
    translation: 'What time does the bus depart?',
    sort_order: 10,
  },
  {
    id: 'card_t11',
    set_id: 'set_travel',
    sentence_parts: ['', '지도', '를 주세요.'],
    key_index: 1,
    translation: 'Please give me a map.',
    sort_order: 11,
  },
  {
    id: 'card_t12',
    set_id: 'set_travel',
    sentence_parts: ['이곳이 ', '명동', '이에요?'],
    key_index: 1,
    translation: 'Is this Myeongdong?',
    sort_order: 12,
  },
  {
    id: 'card_t13',
    set_id: 'set_travel',
    sentence_parts: ['', '기차표', '를 예매했어요.'],
    key_index: 1,
    translation: 'I booked a train ticket.',
    sort_order: 13,
  },
  {
    id: 'card_t14',
    set_id: 'set_travel',
    sentence_parts: ['', '관광버스', '가 몇 시예요?'],
    key_index: 1,
    translation: 'What time is the tour bus?',
    sort_order: 14,
  },
  {
    id: 'card_t15',
    set_id: 'set_travel',
    sentence_parts: ['', '경복궁', '에 가고 싶어요.'],
    key_index: 1,
    translation: 'I want to go to Gyeongbokgung.',
    sort_order: 15,
  },
  {
    id: 'card_t16',
    set_id: 'set_travel',
    sentence_parts: ['', '인천공항', '은 넓어요.'],
    key_index: 1,
    translation: 'Incheon Airport is large.',
    sort_order: 16,
  },
  {
    id: 'card_t17',
    set_id: 'set_travel',
    sentence_parts: ['', '편의점', '이 어디예요?'],
    key_index: 1,
    translation: 'Where is the convenience store?',
    sort_order: 17,
  },
  {
    id: 'card_t18',
    set_id: 'set_travel',
    sentence_parts: ['', '교통카드', '를 충전했어요.'],
    key_index: 1,
    translation: 'I topped up my transit card.',
    sort_order: 18,
  },
  {
    id: 'card_t19',
    set_id: 'set_travel',
    sentence_parts: ['', '사진', '을 찍어도 돼요?'],
    key_index: 1,
    translation: 'Can I take a photo here?',
    sort_order: 19,
  },
  {
    id: 'card_t20',
    set_id: 'set_travel',
    sentence_parts: ['', '입장료', '가 얼마예요?'],
    key_index: 1,
    translation: 'How much is the entrance fee?',
    sort_order: 20,
  },

  // ── Emotions ───────────────────────────────────────────────
  {
    id: 'card_e1',
    set_id: 'set_emotions',
    sentence_parts: ['저는 ', '행복해요', '.'],
    key_index: 1,
    translation: 'I am happy.',
    sort_order: 1,
  },
  {
    id: 'card_e2',
    set_id: 'set_emotions',
    sentence_parts: ['조금 ', '슬퍼요', '.'],
    key_index: 1,
    translation: 'I am a little sad.',
    sort_order: 2,
  },
  {
    id: 'card_e3',
    set_id: 'set_emotions',
    sentence_parts: ['너무 ', '피곤해요', '.'],
    key_index: 1,
    translation: 'I am very tired.',
    sort_order: 3,
  },
  {
    id: 'card_e4',
    set_id: 'set_emotions',
    sentence_parts: ['많이 ', '걱정돼요', '.'],
    key_index: 1,
    translation: 'I am very worried.',
    sort_order: 4,
  },
  {
    id: 'card_e5',
    set_id: 'set_emotions',
    sentence_parts: ['정말 ', '기뻐요', '!'],
    key_index: 1,
    translation: 'I am really glad!',
    sort_order: 5,
  },
  {
    id: 'card_e6',
    set_id: 'set_emotions',
    sentence_parts: ['조금 ', '무서워요', '.'],
    key_index: 1,
    translation: 'I am a little scared.',
    sort_order: 6,
  },
  {
    id: 'card_e7',
    set_id: 'set_emotions',
    sentence_parts: ['', '화가 났어요', '.'],
    key_index: 1,
    translation: 'I am angry.',
    sort_order: 7,
  },
  {
    id: 'card_e8',
    set_id: 'set_emotions',
    sentence_parts: ['', '외로워요', '.'],
    key_index: 1,
    translation: 'I am lonely.',
    sort_order: 8,
  },
  {
    id: 'card_e9',
    set_id: 'set_emotions',
    sentence_parts: ['', '설레요', '.'],
    key_index: 1,
    translation: 'I feel excited / nervous.',
    sort_order: 9,
  },
  {
    id: 'card_e10',
    set_id: 'set_emotions',
    sentence_parts: ['', '부끄러워요', '.'],
    key_index: 1,
    translation: 'I am embarrassed.',
    sort_order: 10,
  },
  {
    id: 'card_e11',
    set_id: 'set_emotions',
    sentence_parts: ['마음이 ', '편해요', '.'],
    key_index: 1,
    translation: 'I feel at ease.',
    sort_order: 11,
  },
  {
    id: 'card_e12',
    set_id: 'set_emotions',
    sentence_parts: ['', '실망했어요', '.'],
    key_index: 1,
    translation: 'I am disappointed.',
    sort_order: 12,
  },
  {
    id: 'card_e13',
    set_id: 'set_emotions',
    sentence_parts: ['', '놀랐어요', '!'],
    key_index: 1,
    translation: 'I was surprised!',
    sort_order: 13,
  },
  {
    id: 'card_e14',
    set_id: 'set_emotions',
    sentence_parts: ['', '그리워요', '.'],
    key_index: 1,
    translation: 'I miss someone.',
    sort_order: 14,
  },
  {
    id: 'card_e15',
    set_id: 'set_emotions',
    sentence_parts: ['', '자신 있어요', '.'],
    key_index: 1,
    translation: 'I am confident.',
    sort_order: 15,
  },
  {
    id: 'card_e16',
    set_id: 'set_emotions',
    sentence_parts: ['', '감동받았어요', '.'],
    key_index: 1,
    translation: 'I was moved / touched.',
    sort_order: 16,
  },
  {
    id: 'card_e17',
    set_id: 'set_emotions',
    sentence_parts: ['', '지루해요', '.'],
    key_index: 1,
    translation: 'I am bored.',
    sort_order: 17,
  },
  {
    id: 'card_e18',
    set_id: 'set_emotions',
    sentence_parts: ['', '신나요', '!'],
    key_index: 1,
    translation: 'I am excited!',
    sort_order: 18,
  },
  {
    id: 'card_e19',
    set_id: 'set_emotions',
    sentence_parts: ['', '긴장돼요', '.'],
    key_index: 1,
    translation: 'I am nervous.',
    sort_order: 19,
  },
  {
    id: 'card_e20',
    set_id: 'set_emotions',
    sentence_parts: ['', '후회해요', '.'],
    key_index: 1,
    translation: 'I regret it.',
    sort_order: 20,
  },

  // ── Numbers ────────────────────────────────────────────────
  {
    id: 'card_num1',
    set_id: 'set_numbers',
    sentence_parts: ['사과가 ', '하나', ' 있어요.'],
    key_index: 1,
    translation: 'There is one apple.',
    sort_order: 1,
  },
  {
    id: 'card_num2',
    set_id: 'set_numbers',
    sentence_parts: ['친구가 ', '둘', ' 왔어요.'],
    key_index: 1,
    translation: 'Two friends came.',
    sort_order: 2,
  },
  {
    id: 'card_num3',
    set_id: 'set_numbers',
    sentence_parts: ['커피 ', '세 잔', ' 주세요.'],
    key_index: 1,
    translation: 'Three cups of coffee, please.',
    sort_order: 3,
  },
  {
    id: 'card_num4',
    set_id: 'set_numbers',
    sentence_parts: ['책이 ', '네 권', ' 있어요.'],
    key_index: 1,
    translation: 'There are four books.',
    sort_order: 4,
  },
  {
    id: 'card_num5',
    set_id: 'set_numbers',
    sentence_parts: ['오늘은 ', '오월 오일', '이에요.'],
    key_index: 1,
    translation: 'Today is May 5th.',
    sort_order: 5,
  },
  {
    id: 'card_num6',
    set_id: 'set_numbers',
    sentence_parts: ['', '천 원', ' 주세요.'],
    key_index: 1,
    translation: 'Please give me 1,000 won.',
    sort_order: 6,
  },
  {
    id: 'card_num7',
    set_id: 'set_numbers',
    sentence_parts: ['', '만 원', '짜리예요.'],
    key_index: 1,
    translation: 'It costs 10,000 won.',
    sort_order: 7,
  },
  {
    id: 'card_num8',
    set_id: 'set_numbers',
    sentence_parts: ['버스가 ', '오 분', ' 후에 와요.'],
    key_index: 1,
    translation: 'The bus comes in 5 minutes.',
    sort_order: 8,
  },
  {
    id: 'card_num9',
    set_id: 'set_numbers',
    sentence_parts: ['나이가 ', '스물 셋', '이에요.'],
    key_index: 1,
    translation: 'I am 23 years old.',
    sort_order: 9,
  },
  {
    id: 'card_num10',
    set_id: 'set_numbers',
    sentence_parts: ['층이 ', '십 층', '이에요.'],
    key_index: 1,
    translation: 'It is the 10th floor.',
    sort_order: 10,
  },
  {
    id: 'card_num11',
    set_id: 'set_numbers',
    sentence_parts: ['버스 번호가 ', '육백이십칠', '번이에요.'],
    key_index: 1,
    translation: 'The bus number is 627.',
    sort_order: 11,
  },
  {
    id: 'card_num12',
    set_id: 'set_numbers',
    sentence_parts: ['', '백 개', '를 샀어요.'],
    key_index: 1,
    translation: 'I bought 100 of them.',
    sort_order: 12,
  },

  // ── Time ───────────────────────────────────────────────────
  {
    id: 'card_ti1',
    set_id: 'set_time',
    sentence_parts: ['지금 ', '몇 시', '예요?'],
    key_index: 1,
    translation: 'What time is it now?',
    sort_order: 1,
  },
  {
    id: 'card_ti2',
    set_id: 'set_time',
    sentence_parts: ['', '오전', ' 열 시에 만나요.'],
    key_index: 1,
    translation: 'We meet at 10 AM.',
    sort_order: 2,
  },
  {
    id: 'card_ti3',
    set_id: 'set_time',
    sentence_parts: ['', '오후', ' 세 시에 끝나요.'],
    key_index: 1,
    translation: 'It ends at 3 PM.',
    sort_order: 3,
  },
  {
    id: 'card_ti4',
    set_id: 'set_time',
    sentence_parts: ['', '어제', ' 뭐 했어요?'],
    key_index: 1,
    translation: 'What did you do yesterday?',
    sort_order: 4,
  },
  {
    id: 'card_ti5',
    set_id: 'set_time',
    sentence_parts: ['', '내일', ' 시간 있어요?'],
    key_index: 1,
    translation: 'Do you have time tomorrow?',
    sort_order: 5,
  },
  {
    id: 'card_ti6',
    set_id: 'set_time',
    sentence_parts: ['', '이번 주', '에 만나요.'],
    key_index: 1,
    translation: 'We meet this week.',
    sort_order: 6,
  },
  {
    id: 'card_ti7',
    set_id: 'set_time',
    sentence_parts: ['', '다음 달', '에 여행 가요.'],
    key_index: 1,
    translation: 'I travel next month.',
    sort_order: 7,
  },
  {
    id: 'card_ti8',
    set_id: 'set_time',
    sentence_parts: ['', '작년', '에 한국에 갔어요.'],
    key_index: 1,
    translation: 'I went to Korea last year.',
    sort_order: 8,
  },
  {
    id: 'card_ti9',
    set_id: 'set_time',
    sentence_parts: ['회의가 ', '언제', '예요?'],
    key_index: 1,
    translation: 'When is the meeting?',
    sort_order: 9,
  },
  {
    id: 'card_ti10',
    set_id: 'set_time',
    sentence_parts: ['', '매일', ' 운동해요.'],
    key_index: 1,
    translation: 'I exercise every day.',
    sort_order: 10,
  },
  {
    id: 'card_ti11',
    set_id: 'set_time',
    sentence_parts: ['', '아침', '에 일어나요.'],
    key_index: 1,
    translation: 'I wake up in the morning.',
    sort_order: 11,
  },
  {
    id: 'card_ti12',
    set_id: 'set_time',
    sentence_parts: ['', '밤', '에 잠을 못 자요.'],
    key_index: 1,
    translation: 'I cannot sleep at night.',
    sort_order: 12,
  },
  {
    id: 'card_ti13',
    set_id: 'set_time',
    sentence_parts: ['', '주말', '에 뭐 해요?'],
    key_index: 1,
    translation: 'What do you do on weekends?',
    sort_order: 13,
  },
  {
    id: 'card_ti14',
    set_id: 'set_time',
    sentence_parts: ['', '새벽', '에 일어났어요.'],
    key_index: 1,
    translation: 'I woke up at dawn.',
    sort_order: 14,
  },
  {
    id: 'card_ti15',
    set_id: 'set_time',
    sentence_parts: ['', '방금', ' 도착했어요.'],
    key_index: 1,
    translation: 'I just arrived.',
    sort_order: 15,
  },

  // ── Body & Health ──────────────────────────────────────────
  {
    id: 'card_b1',
    set_id: 'set_body',
    sentence_parts: ['', '머리', '가 아파요.'],
    key_index: 1,
    translation: 'My head hurts.',
    sort_order: 1,
  },
  {
    id: 'card_b2',
    set_id: 'set_body',
    sentence_parts: ['', '배', '가 고파요.'],
    key_index: 1,
    translation: 'I am hungry.',
    sort_order: 2,
  },
  {
    id: 'card_b3',
    set_id: 'set_body',
    sentence_parts: ['', '목', '이 말라요.'],
    key_index: 1,
    translation: 'I am thirsty.',
    sort_order: 3,
  },
  {
    id: 'card_b4',
    set_id: 'set_body',
    sentence_parts: ['', '다리', '가 아파요.'],
    key_index: 1,
    translation: 'My leg hurts.',
    sort_order: 4,
  },
  {
    id: 'card_b5',
    set_id: 'set_body',
    sentence_parts: ['', '열', '이 있어요.'],
    key_index: 1,
    translation: 'I have a fever.',
    sort_order: 5,
  },
  {
    id: 'card_b6',
    set_id: 'set_body',
    sentence_parts: ['', '감기', '에 걸렸어요.'],
    key_index: 1,
    translation: 'I caught a cold.',
    sort_order: 6,
  },
  {
    id: 'card_b7',
    set_id: 'set_body',
    sentence_parts: ['', '약', '을 먹었어요.'],
    key_index: 1,
    translation: 'I took medicine.',
    sort_order: 7,
  },
  {
    id: 'card_b8',
    set_id: 'set_body',
    sentence_parts: ['', '눈', '이 피곤해요.'],
    key_index: 1,
    translation: 'My eyes are tired.',
    sort_order: 8,
  },
  {
    id: 'card_b9',
    set_id: 'set_body',
    sentence_parts: ['', '손', '을 씻었어요.'],
    key_index: 1,
    translation: 'I washed my hands.',
    sort_order: 9,
  },
  {
    id: 'card_b10',
    set_id: 'set_body',
    sentence_parts: ['', '등', '이 아파요.'],
    key_index: 1,
    translation: 'My back hurts.',
    sort_order: 10,
  },
  {
    id: 'card_b11',
    set_id: 'set_body',
    sentence_parts: ['', '치과', '에 가야 해요.'],
    key_index: 1,
    translation: 'I need to go to the dentist.',
    sort_order: 11,
  },
  {
    id: 'card_b12',
    set_id: 'set_body',
    sentence_parts: ['', '건강', '이 중요해요.'],
    key_index: 1,
    translation: 'Health is important.',
    sort_order: 12,
  },
  {
    id: 'card_b13',
    set_id: 'set_body',
    sentence_parts: ['', '코', '가 막혔어요.'],
    key_index: 1,
    translation: 'My nose is stuffy.',
    sort_order: 13,
  },
  {
    id: 'card_b14',
    set_id: 'set_body',
    sentence_parts: ['', '어깨', '가 결려요.'],
    key_index: 1,
    translation: 'My shoulder is stiff.',
    sort_order: 14,
  },
  {
    id: 'card_b15',
    set_id: 'set_body',
    sentence_parts: ['', '살', '을 빼고 싶어요.'],
    key_index: 1,
    translation: 'I want to lose weight.',
    sort_order: 15,
  },

  // ── Adjectives ─────────────────────────────────────────────
  {
    id: 'card_adj1',
    set_id: 'set_adjectives',
    sentence_parts: ['이 가방이 ', '예뻐요', '.'],
    key_index: 1,
    translation: 'This bag is pretty.',
    sort_order: 1,
  },
  {
    id: 'card_adj2',
    set_id: 'set_adjectives',
    sentence_parts: ['음식이 ', '맛있어요', '.'],
    key_index: 1,
    translation: 'The food is delicious.',
    sort_order: 2,
  },
  {
    id: 'card_adj3',
    set_id: 'set_adjectives',
    sentence_parts: ['날씨가 ', '추워요', '.'],
    key_index: 1,
    translation: 'The weather is cold.',
    sort_order: 3,
  },
  {
    id: 'card_adj4',
    set_id: 'set_adjectives',
    sentence_parts: ['방이 ', '넓어요', '.'],
    key_index: 1,
    translation: 'The room is spacious.',
    sort_order: 4,
  },
  {
    id: 'card_adj5',
    set_id: 'set_adjectives',
    sentence_parts: ['길이 ', '복잡해요', '.'],
    key_index: 1,
    translation: 'The road is crowded.',
    sort_order: 5,
  },
  {
    id: 'card_adj6',
    set_id: 'set_adjectives',
    sentence_parts: ['이 책이 ', '어려워요', '.'],
    key_index: 1,
    translation: 'This book is difficult.',
    sort_order: 6,
  },
  {
    id: 'card_adj7',
    set_id: 'set_adjectives',
    sentence_parts: ['시험이 ', '쉬웠어요', '.'],
    key_index: 1,
    translation: 'The exam was easy.',
    sort_order: 7,
  },
  {
    id: 'card_adj8',
    set_id: 'set_adjectives',
    sentence_parts: ['사람이 ', '많아요', '.'],
    key_index: 1,
    translation: 'There are many people.',
    sort_order: 8,
  },
  {
    id: 'card_adj9',
    set_id: 'set_adjectives',
    sentence_parts: ['목소리가 ', '커요', '.'],
    key_index: 1,
    translation: 'The voice is loud.',
    sort_order: 9,
  },
  {
    id: 'card_adj10',
    set_id: 'set_adjectives',
    sentence_parts: ['값이 ', '비싸요', '.'],
    key_index: 1,
    translation: 'The price is expensive.',
    sort_order: 10,
  },
  {
    id: 'card_adj11',
    set_id: 'set_adjectives',
    sentence_parts: ['가격이 ', '싸요', '.'],
    key_index: 1,
    translation: 'The price is cheap.',
    sort_order: 11,
  },
  {
    id: 'card_adj12',
    set_id: 'set_adjectives',
    sentence_parts: ['하늘이 ', '맑아요', '.'],
    key_index: 1,
    translation: 'The sky is clear.',
    sort_order: 12,
  },
  {
    id: 'card_adj13',
    set_id: 'set_adjectives',
    sentence_parts: ['커피가 ', '뜨거워요', '.'],
    key_index: 1,
    translation: 'The coffee is hot.',
    sort_order: 13,
  },
  {
    id: 'card_adj14',
    set_id: 'set_adjectives',
    sentence_parts: ['이 곳이 ', '조용해요', '.'],
    key_index: 1,
    translation: 'This place is quiet.',
    sort_order: 14,
  },
  {
    id: 'card_adj15',
    set_id: 'set_adjectives',
    sentence_parts: ['사람이 ', '친절해요', '.'],
    key_index: 1,
    translation: 'The person is kind.',
    sort_order: 15,
  },
  {
    id: 'card_adj16',
    set_id: 'set_adjectives',
    sentence_parts: ['길이 ', '멀어요', '.'],
    key_index: 1,
    translation: 'The road is far.',
    sort_order: 16,
  },
  {
    id: 'card_adj17',
    set_id: 'set_adjectives',
    sentence_parts: ['음식이 ', '짜요', '.'],
    key_index: 1,
    translation: 'The food is salty.',
    sort_order: 17,
  },
  {
    id: 'card_adj18',
    set_id: 'set_adjectives',
    sentence_parts: ['날씨가 ', '더워요', '.'],
    key_index: 1,
    translation: 'The weather is hot.',
    sort_order: 18,
  },
  {
    id: 'card_adj19',
    set_id: 'set_adjectives',
    sentence_parts: ['방이 ', '좁아요', '.'],
    key_index: 1,
    translation: 'The room is narrow.',
    sort_order: 19,
  },
  {
    id: 'card_adj20',
    set_id: 'set_adjectives',
    sentence_parts: ['영화가 ', '재미없어요', '.'],
    key_index: 1,
    translation: 'The movie is boring.',
    sort_order: 20,
  },

  // ── Weather & Seasons (set_weather) ────────────────────────
  {
    id: 'card_wx1',
    set_id: 'set_weather',
    sentence_parts: ['지금 ', '봄', '이에요.'],
    key_index: 1,
    translation: 'It is spring now.',
    sort_order: 1,
  },
  {
    id: 'card_wx2',
    set_id: 'set_weather',
    sentence_parts: ['', '여름', '은 더워요.'],
    key_index: 1,
    translation: 'Summer is hot.',
    sort_order: 2,
  },
  {
    id: 'card_wx3',
    set_id: 'set_weather',
    sentence_parts: ['', '가을', '에 단풍이 예뻐요.'],
    key_index: 1,
    translation: 'Autumn foliage is pretty.',
    sort_order: 3,
  },
  {
    id: 'card_wx4',
    set_id: 'set_weather',
    sentence_parts: ['', '겨울', '은 추워요.'],
    key_index: 1,
    translation: 'Winter is cold.',
    sort_order: 4,
  },
  {
    id: 'card_wx5',
    set_id: 'set_weather',
    sentence_parts: ['오늘 ', '비', '가 와요.'],
    key_index: 1,
    translation: 'It is raining today.',
    sort_order: 5,
  },
  {
    id: 'card_wx6',
    set_id: 'set_weather',
    sentence_parts: ['', '눈', '이 내려요.'],
    key_index: 1,
    translation: 'It is snowing.',
    sort_order: 6,
  },
  {
    id: 'card_wx7',
    set_id: 'set_weather',
    sentence_parts: ['', '바람', '이 많이 불어요.'],
    key_index: 1,
    translation: 'The wind is blowing hard.',
    sort_order: 7,
  },
  {
    id: 'card_wx8',
    set_id: 'set_weather',
    sentence_parts: ['하늘에 ', '구름', '이 많아요.'],
    key_index: 1,
    translation: 'There are many clouds in the sky.',
    sort_order: 8,
  },
  {
    id: 'card_wx9',
    set_id: 'set_weather',
    sentence_parts: ['오늘은 ', '맑아요', '.'],
    key_index: 1,
    translation: 'It is clear today.',
    sort_order: 9,
  },
  {
    id: 'card_wx10',
    set_id: 'set_weather',
    sentence_parts: ['날씨가 ', '흐려요', '.'],
    key_index: 1,
    translation: 'The weather is cloudy.',
    sort_order: 10,
  },
  {
    id: 'card_wx11',
    set_id: 'set_weather',
    sentence_parts: ['', '안개', '가 꼈어요.'],
    key_index: 1,
    translation: 'It is foggy.',
    sort_order: 11,
  },
  {
    id: 'card_wx12',
    set_id: 'set_weather',
    sentence_parts: ['', '태풍', '이 와요.'],
    key_index: 1,
    translation: 'A typhoon is coming.',
    sort_order: 12,
  },
  {
    id: 'card_wx13',
    set_id: 'set_weather',
    sentence_parts: ['', '우산', '을 챙기세요.'],
    key_index: 1,
    translation: 'Bring your umbrella.',
    sort_order: 13,
  },
  {
    id: 'card_wx14',
    set_id: 'set_weather',
    sentence_parts: ['오늘 ', '기온', '이 몇 도예요?'],
    key_index: 1,
    translation: "What is today's temperature?",
    sort_order: 14,
  },
  {
    id: 'card_wx15',
    set_id: 'set_weather',
    sentence_parts: ['', '황사', '가 심해요.'],
    key_index: 1,
    translation: 'The yellow dust is bad.',
    sort_order: 15,
  },
  {
    id: 'card_wx16',
    set_id: 'set_weather',
    sentence_parts: ['', '장마', '철이에요.'],
    key_index: 1,
    translation: 'It is the rainy season.',
    sort_order: 16,
  },
  {
    id: 'card_wx17',
    set_id: 'set_weather',
    sentence_parts: ['', '번개', '가 쳤어요.'],
    key_index: 1,
    translation: 'Lightning struck.',
    sort_order: 17,
  },
  {
    id: 'card_wx18',
    set_id: 'set_weather',
    sentence_parts: ['오늘 날씨가 ', '선선해요', '.'],
    key_index: 1,
    translation: 'The weather is cool today.',
    sort_order: 18,
  },
  {
    id: 'card_wx19',
    set_id: 'set_weather',
    sentence_parts: ['', '폭설', '이 내렸어요.'],
    key_index: 1,
    translation: 'Heavy snow fell.',
    sort_order: 19,
  },
  {
    id: 'card_wx20',
    set_id: 'set_weather',
    sentence_parts: ['', '일교차', '가 커요.'],
    key_index: 1,
    translation: 'The temperature difference is big.',
    sort_order: 20,
  },

  // ── Calendar — Days, Months & Time Phrases (set_calendar) ──
  {
    id: 'card_cal1',
    set_id: 'set_calendar',
    sentence_parts: ['', '월요일', '에 학교에 가요.'],
    key_index: 1,
    translation: 'I go to school on Monday.',
    sort_order: 1,
  },
  {
    id: 'card_cal2',
    set_id: 'set_calendar',
    sentence_parts: ['', '화요일', '에 회의가 있어요.'],
    key_index: 1,
    translation: 'I have a meeting on Tuesday.',
    sort_order: 2,
  },
  {
    id: 'card_cal3',
    set_id: 'set_calendar',
    sentence_parts: ['', '수요일', '은 바빠요.'],
    key_index: 1,
    translation: 'Wednesday is busy.',
    sort_order: 3,
  },
  {
    id: 'card_cal4',
    set_id: 'set_calendar',
    sentence_parts: ['', '목요일', '에 운동해요.'],
    key_index: 1,
    translation: 'I exercise on Thursday.',
    sort_order: 4,
  },
  {
    id: 'card_cal5',
    set_id: 'set_calendar',
    sentence_parts: ['', '금요일', '이 좋아요.'],
    key_index: 1,
    translation: 'I like Friday.',
    sort_order: 5,
  },
  {
    id: 'card_cal6',
    set_id: 'set_calendar',
    sentence_parts: ['', '토요일', '에 친구를 만나요.'],
    key_index: 1,
    translation: 'I meet a friend on Saturday.',
    sort_order: 6,
  },
  {
    id: 'card_cal7',
    set_id: 'set_calendar',
    sentence_parts: ['', '일요일', '은 쉬어요.'],
    key_index: 1,
    translation: 'I rest on Sunday.',
    sort_order: 7,
  },
  {
    id: 'card_cal8',
    set_id: 'set_calendar',
    sentence_parts: ['', '일월', '은 추워요.'],
    key_index: 1,
    translation: 'January is cold.',
    sort_order: 8,
  },
  {
    id: 'card_cal9',
    set_id: 'set_calendar',
    sentence_parts: ['', '삼월', '에 봄이 와요.'],
    key_index: 1,
    translation: 'Spring comes in March.',
    sort_order: 9,
  },
  {
    id: 'card_cal10',
    set_id: 'set_calendar',
    sentence_parts: ['', '오월', '에 어린이날이에요.'],
    key_index: 1,
    translation: "Children's Day is in May.",
    sort_order: 10,
  },
  {
    id: 'card_cal11',
    set_id: 'set_calendar',
    sentence_parts: ['', '팔월', '은 제일 더워요.'],
    key_index: 1,
    translation: 'August is the hottest.',
    sort_order: 11,
  },
  {
    id: 'card_cal12',
    set_id: 'set_calendar',
    sentence_parts: ['', '십이월', '에 크리스마스예요.'],
    key_index: 1,
    translation: 'Christmas is in December.',
    sort_order: 12,
  },
  {
    id: 'card_cal13',
    set_id: 'set_calendar',
    sentence_parts: ['', '이번 주', '에 시험이 있어요.'],
    key_index: 1,
    translation: 'I have an exam this week.',
    sort_order: 13,
  },
  {
    id: 'card_cal14',
    set_id: 'set_calendar',
    sentence_parts: ['', '지난 주', '에 뭐 했어요?'],
    key_index: 1,
    translation: 'What did you do last week?',
    sort_order: 14,
  },
  {
    id: 'card_cal15',
    set_id: 'set_calendar',
    sentence_parts: ['', '다음 주', '에 여행 가요.'],
    key_index: 1,
    translation: 'I travel next week.',
    sort_order: 15,
  },
  {
    id: 'card_cal16',
    set_id: 'set_calendar',
    sentence_parts: ['', '이번 달', '에 생일이에요.'],
    key_index: 1,
    translation: 'My birthday is this month.',
    sort_order: 16,
  },
  {
    id: 'card_cal17',
    set_id: 'set_calendar',
    sentence_parts: ['', '지난달', '에 이사했어요.'],
    key_index: 1,
    translation: 'I moved last month.',
    sort_order: 17,
  },
  {
    id: 'card_cal18',
    set_id: 'set_calendar',
    sentence_parts: ['', '올해', '는 바빠요.'],
    key_index: 1,
    translation: 'This year is busy.',
    sort_order: 18,
  },
  {
    id: 'card_cal19',
    set_id: 'set_calendar',
    sentence_parts: ['', '내년', '에 한국에 갈 거예요.'],
    key_index: 1,
    translation: 'I will go to Korea next year.',
    sort_order: 19,
  },
  {
    id: 'card_cal20',
    set_id: 'set_calendar',
    sentence_parts: ['오늘은 ', '무슨 요일', '이에요?'],
    key_index: 1,
    translation: 'What day of the week is today?',
    sort_order: 20,
  },

  // ── Sino-Korean Numbers (set_sino_numbers) ──────────────────
  {
    id: 'card_sn1',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '일', ' 번이에요.'],
    key_index: 1,
    translation: 'It is number one. (1)',
    sort_order: 1,
  },
  {
    id: 'card_sn2',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '이', ' 층이에요.'],
    key_index: 1,
    translation: 'It is the second floor. (2)',
    sort_order: 2,
  },
  {
    id: 'card_sn3',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '삼', ' 분 기다려요.'],
    key_index: 1,
    translation: 'I wait three minutes. (3)',
    sort_order: 3,
  },
  {
    id: 'card_sn4',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '사', ' 월이에요.'],
    key_index: 1,
    translation: 'It is April. (4)',
    sort_order: 4,
  },
  {
    id: 'card_sn5',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '오', ' 번 버스예요.'],
    key_index: 1,
    translation: 'It is bus number five. (5)',
    sort_order: 5,
  },
  {
    id: 'card_sn6',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '육', ' 시예요.'],
    key_index: 1,
    translation: "It is six o'clock. (6)",
    sort_order: 6,
  },
  {
    id: 'card_sn7',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '칠', ' 월이에요.'],
    key_index: 1,
    translation: 'It is July. (7)',
    sort_order: 7,
  },
  {
    id: 'card_sn8',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '팔', ' 층이에요.'],
    key_index: 1,
    translation: 'It is the 8th floor. (8)',
    sort_order: 8,
  },
  {
    id: 'card_sn9',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '구', ' 월이에요.'],
    key_index: 1,
    translation: 'It is September. (9)',
    sort_order: 9,
  },
  {
    id: 'card_sn10',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '십', ' 분이에요.'],
    key_index: 1,
    translation: 'It is ten minutes. (10)',
    sort_order: 10,
  },
  {
    id: 'card_sn11',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '백', ' 원이에요.'],
    key_index: 1,
    translation: 'It is 100 won. (100)',
    sort_order: 11,
  },
  {
    id: 'card_sn12',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '천', ' 원 주세요.'],
    key_index: 1,
    translation: 'Give me 1,000 won. (1,000)',
    sort_order: 12,
  },
  {
    id: 'card_sn13',
    set_id: 'set_sino_numbers',
    sentence_parts: ['', '만', ' 원이에요.'],
    key_index: 1,
    translation: 'It is 10,000 won. (10,000)',
    sort_order: 13,
  },

  // ── Native Korean Numbers (set_native_numbers) ──────────────
  {
    id: 'card_nn1',
    set_id: 'set_native_numbers',
    sentence_parts: ['사과 ', '하나', ' 주세요.'],
    key_index: 1,
    translation: 'One apple please. (1)',
    sort_order: 1,
  },
  {
    id: 'card_nn2',
    set_id: 'set_native_numbers',
    sentence_parts: ['친구가 ', '둘', ' 있어요.'],
    key_index: 1,
    translation: 'I have two friends. (2)',
    sort_order: 2,
  },
  {
    id: 'card_nn3',
    set_id: 'set_native_numbers',
    sentence_parts: ['커피 ', '셋', ' 주세요.'],
    key_index: 1,
    translation: 'Three coffees please. (3)',
    sort_order: 3,
  },
  {
    id: 'card_nn4',
    set_id: 'set_native_numbers',
    sentence_parts: ['의자가 ', '넷', ' 있어요.'],
    key_index: 1,
    translation: 'There are four chairs. (4)',
    sort_order: 4,
  },
  {
    id: 'card_nn5',
    set_id: 'set_native_numbers',
    sentence_parts: ['강아지가 ', '다섯', ' 마리예요.'],
    key_index: 1,
    translation: 'There are five dogs. (5)',
    sort_order: 5,
  },
  {
    id: 'card_nn6',
    set_id: 'set_native_numbers',
    sentence_parts: ['사람이 ', '여섯', ' 명이에요.'],
    key_index: 1,
    translation: 'There are six people. (6)',
    sort_order: 6,
  },
  {
    id: 'card_nn7',
    set_id: 'set_native_numbers',
    sentence_parts: ['책이 ', '일곱', ' 권 있어요.'],
    key_index: 1,
    translation: 'There are seven books. (7)',
    sort_order: 7,
  },
  {
    id: 'card_nn8',
    set_id: 'set_native_numbers',
    sentence_parts: ['오늘 ', '여덟', ' 시에 일어났어요.'],
    key_index: 1,
    translation: 'I woke up at eight today. (8)',
    sort_order: 8,
  },
  {
    id: 'card_nn9',
    set_id: 'set_native_numbers',
    sentence_parts: ['', '아홉', ' 살이에요.'],
    key_index: 1,
    translation: 'I am nine years old. (9)',
    sort_order: 9,
  },
  {
    id: 'card_nn10',
    set_id: 'set_native_numbers',
    sentence_parts: ['', '열', ' 개 주세요.'],
    key_index: 1,
    translation: 'Give me ten. (10)',
    sort_order: 10,
  },
  {
    id: 'card_nn11',
    set_id: 'set_native_numbers',
    sentence_parts: ['나이가 ', '스물', '이에요.'],
    key_index: 1,
    translation: 'I am twenty years old. (20)',
    sort_order: 11,
  },
  {
    id: 'card_nn12',
    set_id: 'set_native_numbers',
    sentence_parts: ['나이가 ', '서른', '이에요.'],
    key_index: 1,
    translation: 'I am thirty years old. (30)',
    sort_order: 12,
  },
  {
    id: 'card_nn13',
    set_id: 'set_native_numbers',
    sentence_parts: ['나이가 ', '마흔', '이에요.'],
    key_index: 1,
    translation: 'I am forty years old. (40)',
    sort_order: 13,
  },
  {
    id: 'card_nn14',
    set_id: 'set_native_numbers',
    sentence_parts: ['나이가 ', '쉰', '이에요.'],
    key_index: 1,
    translation: 'I am fifty years old. (50)',
    sort_order: 14,
  },
  {
    id: 'card_nn15',
    set_id: 'set_native_numbers',
    sentence_parts: ['나이가 ', '예순', '이에요.'],
    key_index: 1,
    translation: 'I am sixty years old. (60)',
    sort_order: 15,
  },

  // ── Counters (set_counters) ─────────────────────────────────
  {
    id: 'card_cnt1',
    set_id: 'set_counters',
    sentence_parts: ['학생이 열 ', '명', ' 있어요.'],
    key_index: 1,
    translation: '명 — counter for people',
    sort_order: 1,
  },
  {
    id: 'card_cnt2',
    set_id: 'set_counters',
    sentence_parts: ['사과 세 ', '개', ' 주세요.'],
    key_index: 1,
    translation: '개 — counter for general objects',
    sort_order: 2,
  },
  {
    id: 'card_cnt3',
    set_id: 'set_counters',
    sentence_parts: ['책 두 ', '권', ' 샀어요.'],
    key_index: 1,
    translation: '권 — counter for books',
    sort_order: 3,
  },
  {
    id: 'card_cnt4',
    set_id: 'set_counters',
    sentence_parts: ['커피 한 ', '잔', ' 주세요.'],
    key_index: 1,
    translation: '잔 — counter for cups/glasses',
    sort_order: 4,
  },
  {
    id: 'card_cnt5',
    set_id: 'set_counters',
    sentence_parts: ['종이 다섯 ', '장', ' 주세요.'],
    key_index: 1,
    translation: '장 — counter for flat things/sheets',
    sort_order: 5,
  },
  {
    id: 'card_cnt6',
    set_id: 'set_counters',
    sentence_parts: ['고양이가 두 ', '마리', ' 있어요.'],
    key_index: 1,
    translation: '마리 — counter for animals',
    sort_order: 6,
  },
  {
    id: 'card_cnt7',
    set_id: 'set_counters',
    sentence_parts: ['차 한 ', '대', ' 있어요.'],
    key_index: 1,
    translation: '대 — counter for vehicles/machines',
    sort_order: 7,
  },
  {
    id: 'card_cnt8',
    set_id: 'set_counters',
    sentence_parts: ['맥주 두 ', '병', ' 주세요.'],
    key_index: 1,
    translation: '병 — counter for bottles',
    sort_order: 8,
  },
  {
    id: 'card_cnt9',
    set_id: 'set_counters',
    sentence_parts: ['세 ', '번', ' 읽었어요.'],
    key_index: 1,
    translation: '번 — counter for times/occurrences',
    sort_order: 9,
  },
  {
    id: 'card_cnt10',
    set_id: 'set_counters',
    sentence_parts: ['옷 한 ', '벌', ' 샀어요.'],
    key_index: 1,
    translation: '벌 — counter for sets of clothing',
    sort_order: 10,
  },

  // ── Fruits (set_fruits) ─────────────────────────────────────
  {
    id: 'card_fr1',
    set_id: 'set_fruits',
    sentence_parts: ['', '사과', '를 좋아해요.'],
    key_index: 1,
    translation: 'I like apples.',
    sort_order: 1,
  },
  {
    id: 'card_fr2',
    set_id: 'set_fruits',
    sentence_parts: ['', '바나나', '가 달아요.'],
    key_index: 1,
    translation: 'Bananas are sweet.',
    sort_order: 2,
  },
  {
    id: 'card_fr3',
    set_id: 'set_fruits',
    sentence_parts: ['', '딸기', '가 빨개요.'],
    key_index: 1,
    translation: 'Strawberries are red.',
    sort_order: 3,
  },
  {
    id: 'card_fr4',
    set_id: 'set_fruits',
    sentence_parts: ['', '수박', '을 잘랐어요.'],
    key_index: 1,
    translation: 'I cut the watermelon.',
    sort_order: 4,
  },
  {
    id: 'card_fr5',
    set_id: 'set_fruits',
    sentence_parts: ['', '포도', '를 먹었어요.'],
    key_index: 1,
    translation: 'I ate grapes.',
    sort_order: 5,
  },
  {
    id: 'card_fr6',
    set_id: 'set_fruits',
    sentence_parts: ['', '복숭아', '가 맛있어요.'],
    key_index: 1,
    translation: 'Peaches are delicious.',
    sort_order: 6,
  },
  {
    id: 'card_fr7',
    set_id: 'set_fruits',
    sentence_parts: ['', '오렌지', '주스를 마셔요.'],
    key_index: 1,
    translation: 'I drink orange juice.',
    sort_order: 7,
  },
  {
    id: 'card_fr8',
    set_id: 'set_fruits',
    sentence_parts: ['', '망고', '가 달콤해요.'],
    key_index: 1,
    translation: 'Mangoes are sweet.',
    sort_order: 8,
  },
  {
    id: 'card_fr9',
    set_id: 'set_fruits',
    sentence_parts: ['', '키위', '가 새콤해요.'],
    key_index: 1,
    translation: 'Kiwis are sour.',
    sort_order: 9,
  },
  {
    id: 'card_fr10',
    set_id: 'set_fruits',
    sentence_parts: ['', '배', '가 시원해요.'],
    key_index: 1,
    translation: 'Korean pears are refreshing.',
    sort_order: 10,
  },
  {
    id: 'card_fr11',
    set_id: 'set_fruits',
    sentence_parts: ['', '감', '을 먹었어요.'],
    key_index: 1,
    translation: 'I ate a persimmon.',
    sort_order: 11,
  },
  {
    id: 'card_fr12',
    set_id: 'set_fruits',
    sentence_parts: ['', '귤', '이 맛있어요.'],
    key_index: 1,
    translation: 'Tangerines are delicious.',
    sort_order: 12,
  },
  {
    id: 'card_fr13',
    set_id: 'set_fruits',
    sentence_parts: ['', '체리', '를 샀어요.'],
    key_index: 1,
    translation: 'I bought cherries.',
    sort_order: 13,
  },
  {
    id: 'card_fr14',
    set_id: 'set_fruits',
    sentence_parts: ['', '파인애플', '이 달아요.'],
    key_index: 1,
    translation: 'Pineapples are sweet.',
    sort_order: 14,
  },
  {
    id: 'card_fr15',
    set_id: 'set_fruits',
    sentence_parts: ['', '레몬', '이 셔요.'],
    key_index: 1,
    translation: 'Lemons are sour.',
    sort_order: 15,
  },

  // ── Vegetables (set_vegetables) ─────────────────────────────
  {
    id: 'card_veg1',
    set_id: 'set_vegetables',
    sentence_parts: ['', '당근', '을 잘랐어요.'],
    key_index: 1,
    translation: 'I cut the carrots.',
    sort_order: 1,
  },
  {
    id: 'card_veg2',
    set_id: 'set_vegetables',
    sentence_parts: ['', '양파', '가 매워요.'],
    key_index: 1,
    translation: 'Onions are pungent.',
    sort_order: 2,
  },
  {
    id: 'card_veg3',
    set_id: 'set_vegetables',
    sentence_parts: ['', '마늘', '을 많이 써요.'],
    key_index: 1,
    translation: 'I use a lot of garlic.',
    sort_order: 3,
  },
  {
    id: 'card_veg4',
    set_id: 'set_vegetables',
    sentence_parts: ['', '고추', '가 매워요.'],
    key_index: 1,
    translation: 'Chili peppers are spicy.',
    sort_order: 4,
  },
  {
    id: 'card_veg5',
    set_id: 'set_vegetables',
    sentence_parts: ['', '배추', '로 김치를 만들어요.'],
    key_index: 1,
    translation: 'I make kimchi with cabbage.',
    sort_order: 5,
  },
  {
    id: 'card_veg6',
    set_id: 'set_vegetables',
    sentence_parts: ['', '시금치', '를 볶았어요.'],
    key_index: 1,
    translation: 'I stir-fried spinach.',
    sort_order: 6,
  },
  {
    id: 'card_veg7',
    set_id: 'set_vegetables',
    sentence_parts: ['', '오이', '가 시원해요.'],
    key_index: 1,
    translation: 'Cucumbers are refreshing.',
    sort_order: 7,
  },
  {
    id: 'card_veg8',
    set_id: 'set_vegetables',
    sentence_parts: ['', '감자', '를 구웠어요.'],
    key_index: 1,
    translation: 'I roasted potatoes.',
    sort_order: 8,
  },
  {
    id: 'card_veg9',
    set_id: 'set_vegetables',
    sentence_parts: ['', '고구마', '가 달아요.'],
    key_index: 1,
    translation: 'Sweet potatoes are sweet.',
    sort_order: 9,
  },
  {
    id: 'card_veg10',
    set_id: 'set_vegetables',
    sentence_parts: ['', '토마토', '를 샀어요.'],
    key_index: 1,
    translation: 'I bought tomatoes.',
    sort_order: 10,
  },
  {
    id: 'card_veg11',
    set_id: 'set_vegetables',
    sentence_parts: ['', '파', '를 썰었어요.'],
    key_index: 1,
    translation: 'I chopped green onions.',
    sort_order: 11,
  },
  {
    id: 'card_veg12',
    set_id: 'set_vegetables',
    sentence_parts: ['', '버섯', '을 넣었어요.'],
    key_index: 1,
    translation: 'I added mushrooms.',
    sort_order: 12,
  },
  {
    id: 'card_veg13',
    set_id: 'set_vegetables',
    sentence_parts: ['', '콩나물', '국을 끓였어요.'],
    key_index: 1,
    translation: 'I made bean sprout soup.',
    sort_order: 13,
  },
  {
    id: 'card_veg14',
    set_id: 'set_vegetables',
    sentence_parts: ['', '브로콜리', '를 쪘어요.'],
    key_index: 1,
    translation: 'I steamed broccoli.',
    sort_order: 14,
  },
  {
    id: 'card_veg15',
    set_id: 'set_vegetables',
    sentence_parts: ['', '호박', '을 볶았어요.'],
    key_index: 1,
    translation: 'I stir-fried zucchini.',
    sort_order: 15,
  },

  // ── Drinks (set_drinks) ─────────────────────────────────────
  {
    id: 'card_dr1',
    set_id: 'set_drinks',
    sentence_parts: ['', '물', '을 마셔요.'],
    key_index: 1,
    translation: 'I drink water.',
    sort_order: 1,
  },
  {
    id: 'card_dr2',
    set_id: 'set_drinks',
    sentence_parts: ['아이스 ', '아메리카노', '를 마셔요.'],
    key_index: 1,
    translation: 'I drink an iced Americano.',
    sort_order: 2,
  },
  {
    id: 'card_dr3',
    set_id: 'set_drinks',
    sentence_parts: ['', '녹차', '를 좋아해요.'],
    key_index: 1,
    translation: 'I like green tea.',
    sort_order: 3,
  },
  {
    id: 'card_dr4',
    set_id: 'set_drinks',
    sentence_parts: ['', '우유', '를 매일 마셔요.'],
    key_index: 1,
    translation: 'I drink milk every day.',
    sort_order: 4,
  },
  {
    id: 'card_dr5',
    set_id: 'set_drinks',
    sentence_parts: ['오렌지 ', '주스', '를 마셨어요.'],
    key_index: 1,
    translation: 'I drank orange juice.',
    sort_order: 5,
  },
  {
    id: 'card_dr6',
    set_id: 'set_drinks',
    sentence_parts: ['', '맥주', ' 한 잔 할래요?'],
    key_index: 1,
    translation: 'Want a glass of beer?',
    sort_order: 6,
  },
  {
    id: 'card_dr7',
    set_id: 'set_drinks',
    sentence_parts: ['', '소주', '를 마셨어요.'],
    key_index: 1,
    translation: 'I drank soju.',
    sort_order: 7,
  },
  {
    id: 'card_dr8',
    set_id: 'set_drinks',
    sentence_parts: ['', '막걸리', '가 맛있어요.'],
    key_index: 1,
    translation: 'Makgeolli is delicious.',
    sort_order: 8,
  },
  {
    id: 'card_dr9',
    set_id: 'set_drinks',
    sentence_parts: ['', '탄산수', '를 샀어요.'],
    key_index: 1,
    translation: 'I bought sparkling water.',
    sort_order: 9,
  },
  {
    id: 'card_dr10',
    set_id: 'set_drinks',
    sentence_parts: ['', '홍차', '를 끓였어요.'],
    key_index: 1,
    translation: 'I brewed black tea.',
    sort_order: 10,
  },
  {
    id: 'card_dr11',
    set_id: 'set_drinks',
    sentence_parts: ['', '라떼', '가 달콤해요.'],
    key_index: 1,
    translation: 'The latte is sweet.',
    sort_order: 11,
  },
  {
    id: 'card_dr12',
    set_id: 'set_drinks',
    sentence_parts: ['', '식혜', '를 마셨어요.'],
    key_index: 1,
    translation: 'I drank sikhye (rice punch).',
    sort_order: 12,
  },
  {
    id: 'card_dr13',
    set_id: 'set_drinks',
    sentence_parts: ['', '보리차', '를 끓여요.'],
    key_index: 1,
    translation: 'I brew barley tea.',
    sort_order: 13,
  },
  {
    id: 'card_dr14',
    set_id: 'set_drinks',
    sentence_parts: ['', '에너지 드링크', '를 마셨어요.'],
    key_index: 1,
    translation: 'I drank an energy drink.',
    sort_order: 14,
  },
  {
    id: 'card_dr15',
    set_id: 'set_drinks',
    sentence_parts: ['', '커피우유', '가 맛있어요.'],
    key_index: 1,
    translation: 'Coffee milk is delicious.',
    sort_order: 15,
  },

  // ── Home & House (set_home) ─────────────────────────────────
  {
    id: 'card_hm1',
    set_id: 'set_home',
    sentence_parts: ['', '거실', '이 넓어요.'],
    key_index: 1,
    translation: 'The living room is spacious.',
    sort_order: 1,
  },
  {
    id: 'card_hm2',
    set_id: 'set_home',
    sentence_parts: ['', '주방', '에서 요리해요.'],
    key_index: 1,
    translation: 'I cook in the kitchen.',
    sort_order: 2,
  },
  {
    id: 'card_hm3',
    set_id: 'set_home',
    sentence_parts: ['', '침실', '이 아늑해요.'],
    key_index: 1,
    translation: 'The bedroom is cozy.',
    sort_order: 3,
  },
  {
    id: 'card_hm4',
    set_id: 'set_home',
    sentence_parts: ['', '화장실', '이 어디예요?'],
    key_index: 1,
    translation: 'Where is the bathroom?',
    sort_order: 4,
  },
  {
    id: 'card_hm5',
    set_id: 'set_home',
    sentence_parts: ['', '현관', '에서 신발을 벗어요.'],
    key_index: 1,
    translation: 'I take off shoes at the entrance.',
    sort_order: 5,
  },
  {
    id: 'card_hm6',
    set_id: 'set_home',
    sentence_parts: ['', '소파', '에 앉았어요.'],
    key_index: 1,
    translation: 'I sat on the sofa.',
    sort_order: 6,
  },
  {
    id: 'card_hm7',
    set_id: 'set_home',
    sentence_parts: ['', '냉장고', '를 열었어요.'],
    key_index: 1,
    translation: 'I opened the refrigerator.',
    sort_order: 7,
  },
  {
    id: 'card_hm8',
    set_id: 'set_home',
    sentence_parts: ['', '세탁기', '를 돌렸어요.'],
    key_index: 1,
    translation: 'I ran the washing machine.',
    sort_order: 8,
  },
  {
    id: 'card_hm9',
    set_id: 'set_home',
    sentence_parts: ['', '텔레비전', '을 봐요.'],
    key_index: 1,
    translation: 'I watch TV.',
    sort_order: 9,
  },
  {
    id: 'card_hm10',
    set_id: 'set_home',
    sentence_parts: ['', '에어컨', '을 켰어요.'],
    key_index: 1,
    translation: 'I turned on the air conditioner.',
    sort_order: 10,
  },
  {
    id: 'card_hm11',
    set_id: 'set_home',
    sentence_parts: ['', '침대', '에 누웠어요.'],
    key_index: 1,
    translation: 'I lay down on the bed.',
    sort_order: 11,
  },
  {
    id: 'card_hm12',
    set_id: 'set_home',
    sentence_parts: ['', '베개', '가 부드러워요.'],
    key_index: 1,
    translation: 'The pillow is soft.',
    sort_order: 12,
  },
  {
    id: 'card_hm13',
    set_id: 'set_home',
    sentence_parts: ['', '이불', '을 덮었어요.'],
    key_index: 1,
    translation: 'I covered myself with a blanket.',
    sort_order: 13,
  },
  {
    id: 'card_hm14',
    set_id: 'set_home',
    sentence_parts: ['', '창문', '을 열었어요.'],
    key_index: 1,
    translation: 'I opened the window.',
    sort_order: 14,
  },
  {
    id: 'card_hm15',
    set_id: 'set_home',
    sentence_parts: ['', '식탁', '에 앉아요.'],
    key_index: 1,
    translation: 'I sit at the dining table.',
    sort_order: 15,
  },
  {
    id: 'card_hm16',
    set_id: 'set_home',
    sentence_parts: ['', '전자레인지', '로 데웠어요.'],
    key_index: 1,
    translation: 'I heated it in the microwave.',
    sort_order: 16,
  },
  {
    id: 'card_hm17',
    set_id: 'set_home',
    sentence_parts: ['', '책상', '에서 공부해요.'],
    key_index: 1,
    translation: 'I study at the desk.',
    sort_order: 17,
  },
  {
    id: 'card_hm18',
    set_id: 'set_home',
    sentence_parts: ['', '의자', '를 당겼어요.'],
    key_index: 1,
    translation: 'I pulled out the chair.',
    sort_order: 18,
  },
  {
    id: 'card_hm19',
    set_id: 'set_home',
    sentence_parts: ['', '옷장', '을 열었어요.'],
    key_index: 1,
    translation: 'I opened the wardrobe.',
    sort_order: 19,
  },
  {
    id: 'card_hm20',
    set_id: 'set_home',
    sentence_parts: ['', '욕조', '에 물을 받았어요.'],
    key_index: 1,
    translation: 'I filled the bathtub with water.',
    sort_order: 20,
  },
  {
    id: 'card_hm21',
    set_id: 'set_home',
    sentence_parts: ['', '샤워기', '가 고장났어요.'],
    key_index: 1,
    translation: 'The shower is broken.',
    sort_order: 21,
  },
  {
    id: 'card_hm22',
    set_id: 'set_home',
    sentence_parts: ['', '선반', '에 올려놨어요.'],
    key_index: 1,
    translation: 'I put it on the shelf.',
    sort_order: 22,
  },
  {
    id: 'card_hm23',
    set_id: 'set_home',
    sentence_parts: ['', '전등', '을 껐어요.'],
    key_index: 1,
    translation: 'I turned off the light.',
    sort_order: 23,
  },
  {
    id: 'card_hm24',
    set_id: 'set_home',
    sentence_parts: ['', '계단', '을 올라갔어요.'],
    key_index: 1,
    translation: 'I went up the stairs.',
    sort_order: 24,
  },
  {
    id: 'card_hm25',
    set_id: 'set_home',
    sentence_parts: ['', '베란다', '에 빨래를 널었어요.'],
    key_index: 1,
    translation: 'I hung laundry on the balcony.',
    sort_order: 25,
  },
];

module.exports = { flashcards };
